---
abstract: 'Manipulate metadata in audio files'
author:
  - 'Egor Shipovalov <kogdaugodno@gmail.com>'
build_requires:
  Cwd: 0
  File::Basename: 0
  File::Copy: 0
  File::Spec: 0
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-Metadata
requires:
  Any::Moose: 0
  IO::File: 0
  List::Util: 0
  Module::Find: 0
  Path::Class: 0
  autodie: 0
version: 0.11
